### ISSUE TITLE
Reset password code is wrong.

### ISSUE THREAD

**Issue by itsSagarBro** [dominic-ks/bdvs-password-reset#21]
When I am calling for API for resetting the password "https://myurl.com/wp-json/bdpwr/v1/reset-password?email=mymail" " the mail is receiving very well, but the code I have received is random characters, but I need a 4 or a 6 digit OTP instead of Random characters.

![image](https://github.com/dominic-ks/bdvs-password-reset/assets/64249963/fac02592-1c0c-4fda-9697-fddfaeb3f343)

**Comment by itsSagarBro** [comment]
@dominic-ks

**Comment by dominic-ks** [comment]
Hello @itsSagarBro, it's not wrong, that is the code that the plugin has produced. The defaults for the code were changed recently to improve security in the default set up and will need to remain this way until we have some sort of rate limiting or ability to block users from resetting passwords after a given number of failed reset attempts. 

Check out the notice in the README.md:

- [https://github.com/dominic-ks/bdvs-password-reset#important-notice](https://github.com/dominic-ks/bdvs-password-reset#important-notice)

As noted there, you can change the code using the `bdpwr_code_length` and `bdpwr_selection_string` filters. Examples of these are documented on wordpress.org:

- [https://wordpress.org/plugins/bdvs-password-reset/](https://wordpress.org/plugins/bdvs-password-reset/)

I'm going to close this, because I don't believe there is an issue here, but let me know if you need anything else.

**Comment by itsSagarBro** [comment]
Thanks for the reply, I have already figured out how to do it, just by changing parameters in functions.php, according to my use-case.

**Comment by dominic-ks** [comment]
@itsSagarBro Great, glad it's working for you.
